// TCLL (Twisted Corners Last Layer) — two sibling sets, TCLL+ and TCLL-,
// each grouped by 8 named shapes (Hammer, Spaceship, Stollery, Pinwheel,
// Two-Face, Turtle, Pinwheel Poser, Gun), numbered within the group the same
// way cube2x2Cll.js numbers its shapes (e.g. Hammer 1..Hammer 6). Pinwheel has
// only 3 cases and Two-Face only 4, matching the source — it lists no more
// for those shapes. Supplied by this project's user as "tcll.txt", which
// gives multiple algorithms per named shape (one per AUF/recognition angle,
// not alternates for the same case) — every one is a distinct case here,
// not just the first. Parenthesized AUF prefixes (e.g. "(U2)") are kept as
// real leading moves with the cosmetic parens stripped; the one "(U/U')"
// (either AUF works) took the first option, same convention as cube2x2Cll.js.
// Every algorithm was parsed and round-trip-verified against the real
// `cubing` 2x2x2 engine, with no duplicate patterns within either set.
export const tcll2x2Sets = [
  {
    id: "tcll-plus",
    name: "TCLL+",
    source: 'Supplied from "tcll.txt"',
    cases: [
      { name: "Hammer 1", alg: "R' F R F' R' F R F'", group: "Hammer" },
      { name: "Hammer 2", alg: "y' R' U2 R U' F R' F'", group: "Hammer" },
      { name: "Hammer 3", alg: "y' U R' U' R U' R2 F R F' R", group: "Hammer" },
      { name: "Hammer 4", alg: "U2 R' F' R U2 R U R' F2", group: "Hammer" },
      { name: "Hammer 5", alg: "U R' U R U' R U' R2 F R2 F'", group: "Hammer" },
      { name: "Hammer 6", alg: "y' U' R' U' R' F R F' R U R' U' R", group: "Hammer" },
      { name: "Spaceship 1", alg: "y' U2 R' U' R U R' U' R", group: "Spaceship" },
      { name: "Spaceship 2", alg: "U R' F R F' R' F R U R U' R' F'", group: "Spaceship" },
      { name: "Spaceship 3", alg: "U R U' R' U R2 U' R' F R' F'", group: "Spaceship" },
      { name: "Spaceship 4", alg: "U R U' R2 F R U R U' R' F'", group: "Spaceship" },
      { name: "Spaceship 5", alg: "U R U2' R' U R' F R F' R U' R'", group: "Spaceship" },
      { name: "Spaceship 6", alg: "U2 R U' R' F R F' R U R2 U' R U' R'", group: "Spaceship" },
      { name: "Stollery 1", alg: "R U R' U F' R U' R' F2", group: "Stollery" },
      { name: "Stollery 2", alg: "U2 R' F R U' F' R U2 R' F2", group: "Stollery" },
      { name: "Stollery 3", alg: "U F R' F' R U2 R U R2 F R F'", group: "Stollery" },
      { name: "Stollery 4", alg: "R U R' F R' F' R U R U R'", group: "Stollery" },
      { name: "Stollery 5", alg: "U' R2 F R F' U R U' R U' R2", group: "Stollery" },
      { name: "Stollery 6", alg: "R' U' F R F' U R2 U' R'", group: "Stollery" },
      { name: "Pinwheel 1", alg: "y' F' R U R U2 R2 F' U R F'", group: "Pinwheel" },
      { name: "Pinwheel 2", alg: "y' R' U' R U R' U2 F R' F' R U R", group: "Pinwheel" },
      { name: "Pinwheel 3", alg: "F R F' U2 R U' R2 F R2 F'", group: "Pinwheel" },
      { name: "Two-Face 1", alg: "y' U R2 U' R2 U R' U R U' R'", group: "Two-Face" },
      { name: "Two-Face 2", alg: "y' U R' U2 R' F R F' R", group: "Two-Face" },
      { name: "Two-Face 3", alg: "R U' R' U F' R' F' R F", group: "Two-Face" },
      { name: "Two-Face 4", alg: "U R U R' U2 R' F R F' U R U2 R'", group: "Two-Face" },
      { name: "Turtle 1", alg: "R U' R' U R U' R'", group: "Turtle" },
      { name: "Turtle 2", alg: "y R U' R' F2 R U R' F' R' F R", group: "Turtle" },
      { name: "Turtle 3", alg: "U F R' F' R U' R' F R F' R U' R'", group: "Turtle" },
      { name: "Turtle 4", alg: "U2 y' R' U' R U' F R2 F'", group: "Turtle" },
      { name: "Turtle 5", alg: "U2 R' F R F' U2 R U2 R'", group: "Turtle" },
      { name: "Turtle 6", alg: "U2 R U R2 F R F' U2 R U' R'", group: "Turtle" },
      { name: "Pinwheel Poser 1", alg: "U' R2 F R2 F' R' U' F R F'", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 2", alg: "U' R' F R2 F' R U R' U2 R'", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 3", alg: "R U R' U2 R' F R F' R U' R'", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 4", alg: "y U2 F' R U R2 F' R", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 5", alg: "R U' R2 F R F'", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 6", alg: "U2 F' U R' F2 R F", group: "Pinwheel Poser" },
      { name: "Gun 1", alg: "R U' R' U2 R U2 R'", group: "Gun" },
      { name: "Gun 2", alg: "y U' F' R' F2 R F' R' F R2 U' R'", group: "Gun" },
      { name: "Gun 3", alg: "R' F R F' U R U' R'", group: "Gun" },
      { name: "Gun 4", alg: "R U' R' U R U2 R' F R' F' R", group: "Gun" },
      { name: "Gun 5", alg: "U2 R U R' U R U R2 F R F'", group: "Gun" },
      { name: "Gun 6", alg: "U R U2 R' F R F' R U R2", group: "Gun" },
    ],
  },
  {
    id: "tcll-minus",
    name: "TCLL-",
    source: 'Supplied from "tcll.txt"',
    cases: [
      { name: "Hammer 1", alg: "U' x U R' U' R U R' U' R x'", group: "Hammer" },
      { name: "Hammer 2", alg: "y' U' F R2 F' U R' U R", group: "Hammer" },
      { name: "Hammer 3", alg: "U2 R U R' U2 F R' F' R2 U' R'", group: "Hammer" },
      { name: "Hammer 4", alg: "U' R U R' F R' F' R U' R U2 R'", group: "Hammer" },
      { name: "Hammer 5", alg: "R' U2 R' U2 R U' R' F R F'", group: "Hammer" },
      { name: "Hammer 6", alg: "R U' R U' R' F R' F' R U' R'", group: "Hammer" },
      { name: "Spaceship 1", alg: "R U R' U' R U R'", group: "Spaceship" },
      { name: "Spaceship 2", alg: "y F U' R U R' U R U R' F'", group: "Spaceship" },
      { name: "Spaceship 3", alg: "U' R U R' F R' F' R U R' F R F'", group: "Spaceship" },
      { name: "Spaceship 4", alg: "U' R' F R F' U R U2 R2 F R F'", group: "Spaceship" },
      { name: "Spaceship 5", alg: "y' U R' U R U R' F R' F' R U' R", group: "Spaceship" },
      { name: "Spaceship 6", alg: "y U' R' F U' R' F R2 U' R' U2 R", group: "Spaceship" },
      { name: "Stollery 1", alg: "U R2 U R2 U' R U2 R' U2 R", group: "Stollery" },
      { name: "Stollery 2", alg: "y' R2 F R' F' U' R U R'", group: "Stollery" },
      { name: "Stollery 3", alg: "F R' F' U R2 U R2' U' R", group: "Stollery" },
      { name: "Stollery 4", alg: "U2 R U' R' U' R' F R F' R U' R'", group: "Stollery" },
      { name: "Stollery 5", alg: "y' R2 F' R U2 R U2 R' F R", group: "Stollery" },
      { name: "Stollery 6", alg: "U2 R U' R' U R U2 R2 F R F'", group: "Stollery" },
      { name: "Pinwheel 1", alg: "R2 U R' U R' U2 R U2 R' U2 R", group: "Pinwheel" },
      { name: "Pinwheel 2", alg: "R' U2 R' U2 R2 F R' F' R'", group: "Pinwheel" },
      { name: "Pinwheel 3", alg: "y' R2 F' R U2 R U R' F2 R", group: "Pinwheel" },
      { name: "Two-Face 1", alg: "R2 U R' U R U2 R' U2 R'", group: "Two-Face" },
      { name: "Two-Face 2", alg: "U2 R2 U' R' F R' F' R U2 R'", group: "Two-Face" },
      { name: "Two-Face 3", alg: "U F' R' F R F U' R U R'", group: "Two-Face" },
      { name: "Two-Face 4", alg: "U R' F R F' R U2 R' U' R U R'", group: "Two-Face" },
      { name: "Turtle 1", alg: "y U' L' U L U' L' U L", group: "Turtle" },
      { name: "Turtle 2", alg: "R U2 R' U R' U' F R F' U R", group: "Turtle" },
      { name: "Turtle 3", alg: "y' U2 R' U' R U R' U R' F R F' R", group: "Turtle" },
      { name: "Turtle 4", alg: "U R U R' U y L' U2 L", group: "Turtle" },
      { name: "Turtle 5", alg: "U' R U2 R' U2 F R' F' R", group: "Turtle" },
      { name: "Turtle 6", alg: "R U' R' U2 R U R2 F R F'", group: "Turtle" },
      { name: "Pinwheel Poser 1", alg: "y U' R U' R' U F R U2 R' F2", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 2", alg: "R U2 R U' R' F R2 F' R", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 3", alg: "y' U' R' U2' F R' F' R2", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 4", alg: "U F R' F' R2 U R'", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 5", alg: "U R U R' F R' F' R U2 R U' R'", group: "Pinwheel Poser" },
      { name: "Pinwheel Poser 6", alg: "F' R' F2 R U' F", group: "Pinwheel Poser" },
      { name: "Gun 1", alg: "U R U2 R' U2 R U R'", group: "Gun" },
      { name: "Gun 2", alg: "U2 F R U2 R' F R U' R2 F R", group: "Gun" },
      { name: "Gun 3", alg: "U R U R' U' F R' F' R", group: "Gun" },
      { name: "Gun 4", alg: "U2 F R' F' R2 U' R' U' R U' R'", group: "Gun" },
      { name: "Gun 5", alg: "y' U' R' F R' F' R U2 R", group: "Gun" },
      { name: "Gun 6", alg: "R2 U R' F R F' R' U' R", group: "Gun" },
    ],
  },
];
