// Cube Shape — the slash sequence(s) needed to bring a scrambled Square-1 back
// to a cube shape before corner/edge algorithms apply, one case per named
// shape-pair (e.g. "Kite / Kite"), grouped by how many slash moves the fix
// takes (this project's user asked for exactly that grouping: 7 groups, "1
// Slash" through "7 Slashes").
//
// Source: cubingapp.com (cubingapp.com/algorithms/SQ1-Cube-Shape). Where the
// source listed more than one algorithm for a case ("X or Y"), only the
// first-listed algorithm is kept, per the project's usual convention for
// alternates.
const source = "cubingapp.com (cubingapp.com/algorithms/SQ1-Cube-Shape)";

const cases = [
  { name: "Kite / Kite", alg: "/", group: "1 Slash" },
  { name: "Barrel / Barrel", alg: "/ (3,3) /", group: "2 Slashes" },
  { name: "Left Fist / Right Fist", alg: "/ (3,0) / (-1,1)", group: "2 Slashes" },
  { name: "Right Fist / Left Fist", alg: "/ (3,0) /", group: "2 Slashes" },
  { name: "Square / Shield", alg: "/ (0,1) / (0,3) /", group: "3 Slashes" },
  { name: "Shield / Square", alg: "/ (-1,0) / (-3,0) /", group: "3 Slashes" },
  { name: "Muffin / Square", alg: "/ (2,0) / (3,0) /", group: "3 Slashes" },
  { name: "Square / Muffin", alg: "/ (0,-2) / (0,-3) /", group: "3 Slashes" },
  { name: "Left Pawn / Right Pawn", alg: "/ (-1,4) / (-3,0) /", group: "3 Slashes" },
  { name: "Right Pawn / Left Pawn", alg: "/ (-4,1) / (3,0) /", group: "3 Slashes" },
  { name: "Scallop / Scallop", alg: "/ (1,2) / (-3,-3) /", group: "3 Slashes" },
  { name: "Kite / Scallop", alg: "/ (2,1) / (0,3) /", group: "3 Slashes" },
  { name: "Barrel / Kite", alg: "/ (-3,0) / (-3,0) /", group: "3 Slashes" },
  { name: "Muffin / Muffin", alg: "/ (-2,0) / (3,3) /", group: "3 Slashes" },
  { name: "Shield / Shield", alg: "/ (1,0) / (-3,-3) /", group: "3 Slashes" },
  { name: "Kite / Barrel", alg: "/ (0,3) / (0,3) /", group: "3 Slashes" },
  { name: "Scallop / Kite", alg: "/ (-1,-2) / (-3,0) /", group: "3 Slashes" },
  { name: "Pair / 4-2 Right", alg: "/ (-2,0) / (1,2) / (-3,-3) /", group: "4 Slashes" },
  { name: "Pair / 2-2-2", alg: "/ (0,2) / (-1,0) / (-3,-3) /", group: "4 Slashes" },
  { name: "4-2 Left / Pair", alg: "/ (2,0) / (-2,-1) / (3,3) /", group: "4 Slashes" },
  { name: "2-2-2 / Pair", alg: "/ (-2,0) / (0,1) / (3,3) /", group: "4 Slashes" },
  { name: "Pair / 4-1-1", alg: "/ (-4,0) / (4,-1) / (-3,0) / (-1,1)", group: "4 Slashes" },
  { name: "4-1-1 / Pair", alg: "/ (0,4) / (4,-1) / (-3,0) / (-1,1)", group: "4 Slashes" },
  { name: "Pair / 5-1 Left", alg: "/ (-2,3) / (-2,-1) / (-3,0) / (-1,1)", group: "4 Slashes" },
  { name: "5-1 Left / Pair", alg: "/ (-3,2) / (-2,-1) / (0,-3) / (-1,1)", group: "4 Slashes" },
  { name: "8 Edges / Star", alg: "/ (2,4) / (-2,-1) / (3,3) /", group: "4 Slashes" },
  { name: "5-1 Right / Pair", alg: "/ (3,-2) / (-1,-2) / (0,-3) /", group: "4 Slashes" },
  { name: "Pair / 5-1 Right", alg: "/ (2,-3) / (-1,-2) / (-3,0) /", group: "4 Slashes" },
  { name: "Pair / 4-2 Left", alg: "/ (0,2) / (2,1) / (3,3) /", group: "4 Slashes" },
  { name: "4-2 Right / Pair", alg: "/ (0,4) / (1,0) / (-3,-3) /", group: "4 Slashes" },
  { name: "Shield / Muffin", alg: "/ (0,-3) / (2,1) / (3,0) /", group: "4 Slashes" },
  { name: "Star / 6-2", alg: "/ (2,4) / (-4,1) / (0,3) /", group: "4 Slashes" },
  { name: "6-2 / Star", alg: "/ (-4,-2) / (-1,4) / (-3,0) /", group: "4 Slashes" },
  { name: "Left Fist / Right Pawn", alg: "/ (-1,0) / (0,1) / (0,3) /", group: "4 Slashes" },
  { name: "Left Pawn / Right Fist", alg: "/ (4,0) / (-1,0) / (-3,0) /", group: "4 Slashes" },
  { name: "Right Fist / Left Pawn", alg: "/ (0,-4) / (0,1) / (0,3) /", group: "4 Slashes" },
  { name: "Star / 8 Edges", alg: "/ (-4,-2) / (1,2) / (-3,-3) /", group: "4 Slashes" },
  { name: "Right Pawn / Left Fist", alg: "/ (0,1) / (-1,0) / (-3,0) /", group: "4 Slashes" },
  { name: "Pair / 6", alg: "/ (-4,0) / (-2,-1) / (3,3) /", group: "4 Slashes" },
  { name: "6 / Pair", alg: "/ (0,4) / (1,2) / (-3,-3) /", group: "4 Slashes" },
  { name: "Muffin / Shield", alg: "/ (3,0) / (-1,-2) / (0,-3) /", group: "4 Slashes" },
  { name: "5-1 Left / Arrow", alg: "/ (0,4) / (1,2) / (0,3) / (-1,1)", group: "4 Slashes" },
  { name: "5-1 Right / Arrow", alg: "/ (0,-4) / (2,1) / (0,3) /", group: "4 Slashes" },
  { name: "3-2-1 Right / Arrow", alg: "/ (-1,-2) / (0,1) / (0,3) /", group: "4 Slashes" },
  { name: "Scallop / Barrel", alg: "/ (4,0) / (-1,0) / (-3,-3) /", group: "4 Slashes" },
  { name: "Barrel / Scallop", alg: "/ (0,-4) / (0,1) / (3,3) /", group: "4 Slashes" },
  { name: "Star / 4-4", alg: "/ (-2,-2) / (1,0) / (-3,-3) /", group: "4 Slashes" },
  { name: "Crown / 4-2 Right", alg: "/ (-3,-2) / (1,2) / (0,3) / (-1,1)", group: "4 Slashes" },
  { name: "4-2 Left / Crown", alg: "/ (-2,-3) / (-1,-2) / (-3,0) /", group: "4 Slashes" },
  { name: "4-4 / Star", alg: "/ (2,2) / (0,-1) / (3,3) /", group: "4 Slashes" },
  { name: "Arrow / 5-1 Right", alg: "/ (-4,0) / (-2,-1) / (-3,0) / (-1,1)", group: "4 Slashes" },
  { name: "Arrow / 5-1 Left", alg: "/ (4,0) / (-1,-2) / (-3,0) /", group: "4 Slashes" },
  { name: "Arrow / 3-2-1 Right", alg: "/ (2,0) / (-1,0) / (-3,0) /", group: "4 Slashes" },
  { name: "3-3 / Arrow", alg: "/ (0,-2) / (-1,4) / (-3,0) /", group: "4 Slashes" },
  { name: "4-2 Right / Crown", alg: "/ (-2,-3) / (-1,-2) / (-3,0) /", group: "4 Slashes" },
  { name: "Arrow / 3-2-1 Left", alg: "/ (2,1) / (-1,0) / (-3,0) /", group: "4 Slashes" },
  { name: "3-2-1 Left / Arrow", alg: "/ (0,-2) / (0,1) / (0,3) /", group: "4 Slashes" },
  { name: "Arrow / 3-3", alg: "/ (-2,0) / (-5,2) / (0,3) / (-1,1)", group: "4 Slashes" },
  { name: "Arrow / 4-1-1", alg: "/ (2,0) / (-1,-2) / (-3,0) /", group: "4 Slashes" },
  { name: "4-1-1 / Arrow", alg: "/ (0,-2) / (2,1) / (0,3) /", group: "4 Slashes" },
  { name: "Right Pawn / Right Fist", alg: "/ (0,2) / (0,1) / (0,3) /", group: "4 Slashes" },
  { name: "Right Fist / Right Pawn", alg: "/ (-2,0) / (-1,0) / (-3,0) /", group: "4 Slashes" },
  { name: "Right Pawn / Right Pawn", alg: "/ (-1,2) / (2,2) / (0,-1) / (3,3) /", group: "5 Slashes" },
  { name: "Crown / 4-2 Left", alg: "/ (0,-4) / (3,-2) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "Kite / Right Pawn", alg: "/ (-1,0) / (0,-2) / (0,1) / (0,3) /", group: "5 Slashes" },
  { name: "Scallop / Right Fist", alg: "/ (0,1) / (-4,0) / (4,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "Left Pawn / Scallop", alg: "/ (3,2) / (-3,2) / (1,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Shield / Left Fist", alg: "/ (0,1) / (-2,0) / (-2,5) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "Kite / Left Pawn", alg: "/ (1,0) / (-1,-2) / (0,1) / (0,3) /", group: "5 Slashes" },
  { name: "Scallop / Left Pawn", alg: "/ (-2,-3) / (-2,3) / (-2,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "Right Pawn / Scallop", alg: "/ (-3,-2) / (3,-2) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "Right Fist / Scallop", alg: "/ (-1,0) / (0,4) / (1,-4) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Right Pawn / Kite", alg: "/ (0,-1) / (2,1) / (-1,0) / (-3,0) /", group: "5 Slashes" },
  { name: "Scallop / Left Fist", alg: "/ (0,-1) / (4,0) / (-4,1) / (3,0) /", group: "5 Slashes" },
  { name: "Shield / Kite", alg: "/ (0,-2) / (-1,-2) / (0,1) / (0,3) /", group: "5 Slashes" },
  { name: "Left Fist / Scallop", alg: "/ (1,0) / (0,-4) / (-1,4) / (0,-3) /", group: "5 Slashes" },
  { name: "Muffin / Scallop", alg: "/ (0,2) / (-3,4) / (1,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Kite / Shield", alg: "/ (-2,0) / (2,0) / (-1,0) / (-3,0) /", group: "5 Slashes" },
  { name: "Scallop / Muffin", alg: "/ (-2,0) / (-4,3) / (-2,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "Scallop / Right Pawn", alg: "/ (2,3) / (2,-3) / (2,1) / (3,0) /", group: "5 Slashes" },
  { name: "Barrel / Left Pawn", alg: "/ (1,-2) / (-3,4) / (1,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Left Pawn / Barrel", alg: "/ (2,-1) / (-4,3) / (-2,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "Square / Scallop", alg: "/ (0,-2) / (0,4) / (-2,-1) / (0,-3) / (-1,1)", group: "5 Slashes" },
  { name: "Barrel / Right Pawn", alg: "/ (1,-2) / (4,-3) / (-2,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "Shield / Barrel", alg: "/ (-2,0) / (2,0) / (-1,0) / (-3,-3) /", group: "5 Slashes" },
  { name: "Barrel / Shield", alg: "/ (0,2) / (0,-2) / (0,1) / (3,3) /", group: "5 Slashes" },
  { name: "Left Pawn / Kite", alg: "/ (0,1) / (2,0) / (-1,0) / (-3,0) /", group: "5 Slashes" },
  { name: "Square / Left Pawn", alg: "/ (3,-2) / (0,2) / (1,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Right Pawn / Barrel", alg: "/ (2,-1) / (3,-4) / (1,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Left Pawn / Square", alg: "/ (2,-3) / (-2,0) / (-2,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "Square / Right Pawn", alg: "(1,0) / (0,-1) / (0,2) / (2,1) / (0,3) /", group: "5 Slashes" },
  { name: "Right Pawn / Square", alg: "(0,-1) / (1,0) / (-2,0) / (-1,-2) / (-3,0) /", group: "5 Slashes" },
  { name: "Scallop / Shield", alg: "/ (-2,0) / (4,0) / (2,1) / (3,3) /", group: "5 Slashes" },
  { name: "Scallop / Square", alg: "/ (2,0) / (-4,0) / (1,2) / (3,0) / (-1,1)", group: "5 Slashes" },
  { name: "4-1-1 / Crown", alg: "/ (3,-2) / (0,4) / (1,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Left Pawn / Shield", alg: "/ (0,-1) / (2,-3) / (-1,-2) / (-3,0) /", group: "5 Slashes" },
  { name: "4-2 Right / Arrow", alg: "/ (-4,3) / (-3,2) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "Arrow / 4-2 Right", alg: "/ (-4,3) / (-3,2) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "4-2 Left / Arrow", alg: "/ (-3,4) / (-2,3) / (-1,-2) / (-3,0) /", group: "5 Slashes" },
  { name: "Arrow / 4-2 Left", alg: "/ (0,-3) / (-4,3) / (-2,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "6 / Arrow", alg: "/ (-3,-4) / (-2,3) / (-1,-2) / (-3,0) /", group: "5 Slashes" },
  { name: "Arrow / 6", alg: "/ (-3,-2) / (2,-3) / (-2,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "3-2-1 Right / Pair", alg: "/ (0,-5) / (-3,4) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "3-2-1 Left / Pair", alg: "/ (0,5) / (-3,2) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "Crown / 5-1 Right", alg: "/ (0,3) / (4,0) / (-1,-2) / (-3,0) /", group: "5 Slashes" },
  { name: "5-1 Right / Crown", alg: "/ (3,0) / (0,4) / (1,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Crown / 5-1 Left", alg: "/ (-4,1) / (0,-4) / (0,-1) / (3,3) /", group: "5 Slashes" },
  { name: "Crown / 4-1-1", alg: "/ (-2,3) / (4,0) / (-1,-2) / (-3,0) /", group: "5 Slashes" },
  { name: "Crown / 6", alg: "/ (3,2) / (2,4) / (1,2) / (-3,-3) /", group: "5 Slashes" },
  { name: "3-2-1 Left / Crown", alg: "/ (4,-1) / (2,0) / (-1,-2) / (-3,-3) /", group: "5 Slashes" },
  { name: "Crown / 3-2-1 Left", alg: "/ (-1,4) / (0,2) / (-2,-1) / (-3,-3) / (-1,1)", group: "5 Slashes" },
  { name: "3-2-1 Right / Crown", alg: "/ (0,-3) / (-3,0) / (2,-3) / (-2,-1) / (-3,0) / (-1,1)", group: "5 Slashes" },
  { name: "Crown / 3-2-1 Right", alg: "/ (-3,0) / (0,-3) / (-3,2) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "3-3 / Crown", alg: "/ (-2,1) / (-2,0) / (1,2) / (-3,-3) /", group: "5 Slashes" },
  { name: "Crown / 3-3", alg: "/ (1,-2) / (0,-2) / (-1,-2) / (-3,-3) /", group: "5 Slashes" },
  { name: "5-1 Left / Crown", alg: "/ (-3,0) / (0,-4) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "Pair / 3-2-1 Left", alg: "/ (-5,0) / (-2,3) / (2,1) / (3,0) /", group: "5 Slashes" },
  { name: "Pair / 3-2-1 Right", alg: "(0,2) / (-2,2) / (0,-4) / (2,1) / (0,3) /", group: "5 Slashes" },
  { name: "Muffin / Right Pawn", alg: "/ (0,-1) / (0,2) / (1,2) / (-3,-3) /", group: "5 Slashes" },
  { name: "Left Fist / Shield", alg: "/ (-1,0) / (0,2) / (-5,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Left Pawn / Muffin", alg: "/ (1,0) / (-2,0) / (2,1) / (3,3) /", group: "5 Slashes" },
  { name: "Muffin / Left Pawn", alg: "/ (0,-1) / (0,2) / (-1,-2) / (-3,-3) /", group: "5 Slashes" },
  { name: "6 / Crown", alg: "/ (3,2) / (2,4) / (1,2) / (-3,-3) /", group: "5 Slashes" },
  { name: "Shield / Left Pawn", alg: "/ (1,0) / (3,-2) / (2,1) / (0,3) /", group: "5 Slashes" },
  { name: "Right Pawn / Shield", alg: "/ (1,0) / (-2,3) / (-1,-2) / (-3,0) /", group: "5 Slashes" },
  { name: "Shield / Right Pawn", alg: "/ (0,-1) / (-3,2) / (2,1) / (0,3) /", group: "5 Slashes" },
  { name: "Right Fist / Shield", alg: "/ (-1,-2) / (0,2) / (-5,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Right Pawn / Muffin", alg: "/ (-1,0) / (2,0) / (-2,-1) / (3,3) /", group: "5 Slashes" },
  { name: "Shield / Right Fist", alg: "/ (-1,-2) / (0,2) / (-5,2) / (0,3) / (-1,1)", group: "5 Slashes" },
  { name: "Left Fist / Left Pawn", alg: "/ (0,2) / (0,-4) / (5,-2) / (-3,0) /", group: "5 Slashes" },
  { name: "3-3 / Pair", alg: "/ (0,-2) / (3,0) / (-1,-2) / (0,-3) /", group: "5 Slashes" },
  { name: "Left Pawn / Left Fist", alg: "/ (-2,0) / (4,0) / (2,-5) / (0,3) /", group: "5 Slashes" },
  { name: "Pair / 3-3", alg: "/ (2,0) / (0,-3) / (2,1) / (3,0) /", group: "5 Slashes" },
  { name: "Left Pawn / Left Pawn", alg: "/ (1,0) / (-2,-2) / (-1,-2) / (-3,-3) /", group: "5 Slashes" },
  { name: "Shield / Scallop", alg: "/ (0,2) / (0,-4) / (-1,-2) / (-3,-3) /", group: "5 Slashes" },
  { name: "Barrel / Square", alg: "/ (2,2) / (-2,-1) / (2,2) / (-1,0) / (-3,-3) /", group: "6 Slashes" },
  { name: "Kite / Right Fist", alg: "/ (0,2) / (1,0) / (0,-2) / (2,1) / (0,3) /", group: "6 Slashes" },
  { name: "Observatory / Star", alg: "(1,0) / (0,-2) / (-1,-2) / (2,-3) / (-2,-1) / (-3,0) / (-1,1)", group: "6 Slashes" },
  { name: "Square / Barrel", alg: "/ (2,2) / (-1,2) / (2,2) / (0,-1) / (3,3) /", group: "6 Slashes" },
  { name: "Star / 5-3", alg: "(0,3) / (-4,0) / (-2,-1) / (-3,2) / (2,1) / (0,3) /", group: "6 Slashes" },
  { name: "5-3 / Star", alg: "/ (0,4) / (1,2) / (-2,3) / (-1,-2) / (-3,0) /", group: "6 Slashes" },
  { name: "Star / Observatory", alg: "/ (-2,0) / (-2,-1) / (-3,2) / (-1,-2) / (0,-3) /", group: "6 Slashes" },
  { name: "Square / Left Fist", alg: "/ (0,4) / (-2,-1) / (0,2) / (2,1) / (0,3) /", group: "6 Slashes" },
  { name: "Left Fist / Square", alg: "/ (-4,0) / (1,2) / (-2,0) / (-1,-2) / (-3,0) /", group: "6 Slashes" },
  { name: "Right Fist / Barrel", alg: "/ (-2,0) / (-1,0) / (2,0) / (1,2) / (-3,-3) /", group: "6 Slashes" },
  { name: "Left Fist / Left Fist", alg: "/ (0,-2) / (0,2) / (0,-2) / (0,1) / (0,3) /", group: "6 Slashes" },
  { name: "Arrow / 2-2-2", alg: "/ (0,-1) / (0,2) / (2,1) / (-1,0) / (-3,0) /", group: "6 Slashes" },
  { name: "Muffin / Left Fist", alg: "/ (0,-4) / (1,0) / (0,-2) / (-4,1) / (0,3) /", group: "6 Slashes" },
  { name: "Left Fist / Muffin", alg: "/ (4,0) / (0,-1) / (2,0) / (-1,4) / (-3,0) /", group: "6 Slashes" },
  { name: "Muffin / Right Fist", alg: "/ (0,-4) / (1,2) / (0,-2) / (-4,1) / (0,3) /", group: "6 Slashes" },
  { name: "Right Fist / Muffin", alg: "/ (4,0) / (-2,-1) / (2,0) / (-1,4) / (-3,0) /", group: "6 Slashes" },
  { name: "Right Fist / Right Fist", alg: "/ (2,0) / (-2,0) / (2,0) / (-1,0) / (-3,0) /", group: "6 Slashes" },
  { name: "2-2-2 / Crown", alg: "/ (6,-3) / (2,0) / (2,1) / (-1,0) / (-3,0) /", group: "6 Slashes" },
  { name: "2-2-2 / Arrow", alg: "/ (-1,0) / (2,0) / (0,-2) / (0,1) / (0,3) /", group: "6 Slashes" },
  { name: "Barrel / Right Fist", alg: "/ (0,2) / (0,1) / (0,-2) / (-2,-1) / (3,3) /", group: "6 Slashes" },
  { name: "Left Fist / Barrel", alg: "/ (2,0) / (1,0) / (-2,0) / (-1,-2) / (-3,-3) /", group: "6 Slashes" },
  { name: "Kite / Muffin", alg: "/ (3,2) / (0,-2) / (0,2) / (0,-1) / (3,3) /", group: "6 Slashes" },
  { name: "Muffin / Kite", alg: "/ (2,3) / (-2,0) / (2,0) / (-1,0) / (-3,-3) /", group: "6 Slashes" },
  { name: "Right Fist / Kite", alg: "/ (-2,0) / (0,-1) / (2,0) / (-1,-2) / (-3,0) /", group: "6 Slashes" },
  { name: "Kite / Left Fist", alg: "/ (0,2) / (1,0) / (0,-2) / (-1,-2) / (0,-3) /", group: "6 Slashes" },
  { name: "Left Fist / Kite", alg: "/ (-2,0) / (0,-1) / (2,0) / (-1,-2) / (-3,0) /", group: "6 Slashes" },
  { name: "Barrel / Muffin", alg: "/ (-3,-2) / (0,-2) / (0,2) / (0,-1) / (0,-3) / (-1,1)", group: "6 Slashes" },
  { name: "Muffin / Barrel", alg: "/ (2,3) / (2,0) / (-2,0) / (1,0) / (3,0) / (-1,1)", group: "6 Slashes" },
  { name: "Barrel / Left Fist", alg: "/ (0,-2) / (0,-1) / (0,2) / (2,1) / (3,3) /", group: "6 Slashes" },
  { name: "Crown / 2-2-2", alg: "/ (0,3) / (2,0) / (2,1) / (-1,0) / (-3,0) /", group: "6 Slashes" },
  { name: "Square / Right Fist", alg: "(1,0) / (-1,0) / (0,-4) / (1,2) / (0,-2) / (2,1) / (0,3) /", group: "7 Slashes" },
  { name: "Right Fist / Square", alg: "(0,-1) / (0,1) / (4,0) / (-2,-1) / (2,0) / (-1,-2) / (-3,0) /", group: "7 Slashes" },
  { name: "Kite / Square", alg: "/ (-1,0) / (2,0) / (-2,0) / (2,0) / (-1,0) / (-3,0) /", group: "7 Slashes" },
  { name: "Square / Kite", alg: "/ (0,1) / (0,-2) / (0,2) / (0,-2) / (0,1) / (0,3) /", group: "7 Slashes" },
];

export default {
  id: "cubeShape",
  name: "Cube Shape",
  source,
  cases,
};
